[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200