name: Weekly Rebuild

on:
  schedule:
    - cron: '0 6 * * 1' # Tous les lundis à 6h UTC

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify rebuild
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
